---
title: "README"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

# R code for generating the book ----------------
Compile Hadley’s Advanced R to a PDF according to 
https://brettklamer.com/diversions/statistical/compile-hadleys-advanced-r-programming-to-a-pdf/.

```{r,eval=FALSE}
install.packages("devtools")
# Install R Package Dependencies
devtools::install_github("hadley/sloop")
devtools::install_github("hadley/emo")

# Compile the book
bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book")
```

# Error 1 ---------------------
## Error message
Quitting from lines 4-5 (Introduction.Rmd) 
Error in dev.control(displaylist = if (record) "enable" else "inhibit") : 
  dev.control() called without an open graphics device
## Solution For Mac setup:
Download Quartz X11 at https://www.xquartz.org , install, restart your Mac
install.packages("Cairo")
Test library(Cairo) - if this fails, start over (the rest is the same)
install or update devtools
install posterdown from GitHub
install tinytex
From:https://github.com/brentthorne/posterdown/issues/42

# Error 2 ---------------------
## Error message
Quitting from lines 80-81 (Names-values.Rmd) 
Error in library(lobstr) : there is no package called 'lobstr'
## Solution
install.packages("lobstr")

# Error 3 ---------------------
## Error message
Quitting from lines 535-550 (R6.Rmd) 
Error in (function (cond)  : 
  error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': there is no package called 'RSQLite'
## Solution
install.packages("RSQLite")

# Error 4 ---------------------
## Error message
Quitting from lines 172-176 (OO-tradeoffs.Rmd) 
Error in library(zeallot) : there is no package called 'zeallot'
## Solution
install.packages("zeallot")

# Error 5 ---------------------
## Error message
Quitting from lines 38-40 (Perf-measure.Rmd) 
Error in library(profvis) : there is no package called 'profvis'
## Solution
install.packages("profvis")

# Error 6 ---------------------
## Error message
Quitting from lines 38-40 (Perf-measure.Rmd) 
Error in library(bench) : there is no package called 'bench'
## Solution
install.packages("bench")

# Error 7 ---------------------
## Error message
Quitting from lines 233-234 (Perf-measure.Rmd) 
Error: `ggbeeswarm` must be installed to use `type = "beeswarm"` option.
## Solution
install.packages("ggbeeswarm")

# Error 8 ---------------------
## Error message
! Package fontspec Error: The font "Inconsolata" cannot be found.
## Solution 
1. download Inconsolata and install from https://fonts.google.com/specimen/Inconsolata#standard-styles 
2. restart Rstudio

### ! LaTeX Error: Environment sidebar undefined.
Solution：update rstudio
remotes::install_github('rstudio/rmarkdown')

